# Generated by Django 3.0.2 on 2020-01-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myday', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(verbose_name='journal date')),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='MyDay',
        ),
    ]
